language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
sudo: false
env:
  - DJANGO_VERSION_CEILING=1.11 DJANGO_DB_ENGINE=sqlite
  - DJANGO_VERSION_CEILING=1.11 DJANGO_DB_ENGINE=postgres DJANGO_DB_NAME=testdb DJANGO_DB_USER=postgres
  - DJANGO_VERSION_CEILING=1.11 DJANGO_DB_ENGINE=mysql DJANGO_DB_NAME=testdb DJANGO_DB_USER=travis
  - DJANGO_VERSION_CEILING=1.12 DJANGO_DB_ENGINE=sqlite
  - DJANGO_VERSION_CEILING=1.12 DJANGO_DB_ENGINE=postgres DJANGO_DB_NAME=testdb DJANGO_DB_USER=postgres
  - DJANGO_VERSION_CEILING=1.12 DJANGO_DB_ENGINE=mysql DJANGO_DB_NAME=testdb DJANGO_DB_USER=travis
install:
  - pip install "Django<$DJANGO_VERSION_CEILING" mysqlclient psycopg2
  - "pip install flake8 pylint pylint-django django-nose"
  - "pip install -e ."
before_script:
  - "mysql -e 'create database testdb;'"
  - "psql -c 'create database testdb;' -U postgres"
script:
  - "python setup.py test"
  - "./lint.sh"
matrix:
  exclude:
    - python: 3.6
      env: DJANGO_VERSION_CEILING=1.11 DJANGO_DB_ENGINE=sqlite
    - python: 3.6
      env: DJANGO_VERSION_CEILING=1.11 DJANGO_DB_ENGINE=postgres DJANGO_DB_NAME=testdb DJANGO_DB_USER=postgres
    - python: 3.6
      env: DJANGO_VERSION_CEILING=1.11 DJANGO_DB_ENGINE=mysql DJANGO_DB_NAME=testdb DJANGO_DB_USER=travis
